CREATE TABLE store(id INTEGER PRIMARY KEY,object TEXT,price NUMERIC,quantity INTEGER, tax_percentage NUMERIC);

INSERT INTO store VALUES(1,'PEN',3.4,5,2.5);
INSERT INTO store VALUES(2,'RUBBER',7,5,2);
INSERT INTO store VALUES(3,'COPY',3,5,2);
INSERT INTO store VALUES(4,'PENCIL',3,5,2);
INSERT INTO store VALUES(5,'SOAP',3,5,2);
INSERT INTO store VALUES(6,'POWDER',24,5,2);
INSERT INTO store VALUES(7,'LAYS',3,5,2);
INSERT INTO store VALUES(8,'OATS',3,5,2);
INSERT INTO store VALUES(9,'UNCLE CHIPS',30,5,2);
INSERT INTO store VALUES(10,'CHIPS',3,5,2);
INSERT INTO store VALUES(11,'BANANA CHIPS',3,5,2);
INSERT INTO store VALUES(12,'WAFFLE',15,5,2);
INSERT INTO store VALUES(13,'TOFEE',3,5,2);
INSERT INTO store VALUES(14,'MAGII',3,5,2);
INSERT INTO store VALUES(15,'CHOCKLATE',3,5,2);
INSERT INTO store VALUES(16,'WATER',3,5,2);
INSERT INTO store VALUES(17,'JUICE',3,5,2);

SELECT *FROM store ORDER BY price;
SELECT SUM(price) FROM store;
